export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_POKEMONS_PENDING = 'REQUEST_POKEMONS_PENDING';
export const REQUEST_POKEMONS_SUCCESS = 'REQUEST_POKEMONS_SUCCESS';
export const REQUEST_POKEMONS_FAILED = 'REQUEST_POKEMONS_FAILED';